import { expect, test, type Request } from '@playwright/test';

test('studio feedback emails only opted-in context and retains a draft after Escape', async ({ page }) => {
  const sent: unknown[] = [];
  await page.route('**/v1/feedback', async (route, request: Request) => { sent.push(request.postDataJSON()); await route.fulfill({ status: 204 }); });
  await page.goto('/studio');
  const trigger = page.getByRole('button', { name: 'Feedback', exact: true });
  await trigger.click();
  const dialog = page.getByRole('dialog', { name: 'Help improve TopoStack' });
  await expect(dialog).toBeVisible();
  const send = dialog.getByRole('button', { name: 'Send feedback' });
  await expect(send).toBeDisabled();
  await dialog.getByLabel('Feedback type').selectOption('terrain');
  await dialog.getByLabel('Summary', { exact: true }).fill('Ridge is coarse & missing detail');
  await dialog.getByLabel('Details', { exact: true }).fill('The ridge looks stepped. I expected a smoother elevation source.');
  await expect(send).toBeEnabled();
  const github = new URL((await dialog.getByRole('link', { name: /Continue on GitHub/ }).getAttribute('href'))!);
  expect(github.searchParams.get('title')).toBe('[Terrain data] Ridge is coarse & missing detail');
  await dialog.getByLabel('Email for a reply (optional)').fill('not an address');
  await expect(send).toBeDisabled();
  await dialog.getByLabel('Email for a reply (optional)').fill('maker@example.com');
  await dialog.getByRole('checkbox').check();
  await dialog.getByText('Review report and shared context', { exact: true }).click();
  await expect(dialog.getByRole('textbox', { name: 'Report preview' })).toHaveValue(/selectedLocation/);
  await dialog.getByRole('checkbox').uncheck();
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(trigger).toBeFocused();
  await trigger.click();
  await expect(dialog.getByLabel('Summary', { exact: true })).toHaveValue('Ridge is coarse & missing detail');
  await dialog.getByRole('checkbox').check();
  await send.click();
  await expect(dialog.getByRole('status')).toContainText('Thanks!');
  expect(sent).toHaveLength(1);
  expect(sent[0]).toMatchObject({ kind: 'terrain', summary: 'Ridge is coarse & missing detail', replyTo: 'maker@example.com', context: { selectedLocation: expect.any(Object) } });
  await dialog.getByRole('button', { name: 'Send more feedback' }).click();
  await expect(dialog.getByLabel('Summary', { exact: true })).toHaveValue('');
});

test('mobile feedback keeps long reports when sending fails and survives clipboard denial', async ({ page }) => {
  await page.route('**/v1/feedback', (route) => route.fulfill({ status: 502, contentType: 'application/json', body: '{"error":"Feedback could not be sent."}' }));
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto('/');
  await page.getByRole('button', { name: 'Feedback', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Help improve TopoStack' });
  await dialog.getByLabel('Feedback type').selectOption('lake');
  await dialog.getByLabel('Summary', { exact: true }).fill('Missing lake survey');
  const details = '湖'.repeat(3000);
  await dialog.getByLabel('Details', { exact: true }).fill(details);
  await expect(dialog.getByRole('checkbox')).toHaveCount(0);
  await dialog.getByRole('button', { name: 'Send feedback' }).click();
  const alert = dialog.getByRole('alert');
  await expect(alert).toContainText('could not be sent');
  const link = alert.getByRole('link', { name: /open a GitHub issue and paste the report/ });
  expect(new URL((await link.getAttribute('href'))!).searchParams.has('body')).toBe(false);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('denied')) } }));
  await alert.getByRole('button', { name: 'Copy report' }).click();
  await expect(dialog.getByText('Copy is unavailable.', { exact: false })).toBeVisible();
  await expect(dialog.getByRole('textbox', { name: 'Report preview' })).toHaveValue(new RegExp(details));
  await expect(dialog.getByLabel('Details', { exact: true })).toHaveValue(details);
  const size = await dialog.boundingBox();
  expect(size!.x).toBeGreaterThanOrEqual(0);
  expect(size!.width).toBeLessThanOrEqual(375);
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await dialog.getByRole('button', { name: 'Close feedback' }).click();
  await expect(dialog).not.toBeVisible();
});

test('lake data reporting opens the right category', async ({ page }) => {
  await page.goto('/studio');
  await page.getByRole('tab', { name: 'Water', exact: true }).click();
  await page.getByRole('button', { name: 'Report lake data quality', exact: true }).click();
  await expect(page.getByRole('dialog').getByLabel('Feedback type')).toHaveValue('lake');
});
