import { mkdir, readFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { pinnedDownload } from '../../lib/pinned-download.mjs';
const source = JSON.parse(await readFile('scripts/verify/walden-example/source.json'));
await mkdir('.topostack/walden-example', { recursive: true });
await mkdir('docs/images/walden-example', { recursive: true });
const pdf = '.topostack/walden-example/source.pdf';
await pinnedDownload({ url: source.pdfUrl, sha256: source.pdfSha256, file: pdf, label: 'USGS Walden source' });
const [left, top, right, bottom] = source.crop;
execFileSync('pdftoppm', ['-r', '288', '-x', String(left * 4), '-y', String(top * 4), '-W', String((right-left) * 4), '-H', String((bottom-top) * 4), '-png', '-singlefile', pdf, '.topostack/walden-example/source-crop']);
